language: java
jdk: openjdk8
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: jpG/cOL9nWoVkjq1E7aebgIV1b9qcNW0dauK+3hD50HuVMVFFDGrUql4PNBS+cRvidTfEr3TN6qUnQr8zZGg1brwKe9/0s7Knk0qmKN2mmQzU45eBO1J1UFrFkuP/SOPAI1Vc0YBQcEjBUrnyQkmUwSnZJpToFUrga/XbWToC94RseUsMGoj8tjm3PJTCUoUj6y+s/Q/igtM5B5GicNga39yH18Hp9C0aL7Et1Z2VJlv+gSTnhVvhnA+CzjHhA51w8U1B3h2NCxdagAYwsmGXMKENDotKYuA8LG7C3gFCdOZqWr5qmkKMdNO/qJiVIh9Ig6lWtQgwh1+Cw8l3Za3Ec8abyO5KCzA2R+MAcrzllikQiZNEK4FgTdwSJIAEoLGdgMKN565kaqs2ihAzo7+NmfzwdosgC0XP2HAsOfBr5YIY40NAZhNZ/6mW5BBIAbpFBMqajrB881BG2X5y0fqrgvWI7pm+DWzVK/zziKsfwwkOaBrjzKe8/WzPhWm/dJEmAAop13jpxa3HwT7xETvKJBwh9J4lRFZb6ZyiH1sbJ3W+68pVdyk1JsNjkc31uboZorSdwevdg83IYsaEHWJV87p3SHUEq3pl4lj6crbG8r/ILDtu2wbXR51MCVFxYA+Ag858zYW7Gfd75PmttiGyF7+bwJMfH2x2fJqRHYmNpQ=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-telnet-plugin
